package daywa;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author neo_n
 */
public class Seguidores extends javax.swing.JFrame {

    /**
     * Creates new form Seguidores
     */
    public Seguidores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelSeguidores = new javax.swing.JLabel();
        jPanelImagenUsuario1 = new javax.swing.JPanel();
        jLabelUsuario1 = new javax.swing.JLabel();
        jPanelImagenUsuario2 = new javax.swing.JPanel();
        jLabelUsuario2 = new javax.swing.JLabel();
        jPanelImagenUsuario3 = new javax.swing.JPanel();
        jLabelUsuario3 = new javax.swing.JLabel();
        jPanelImagenUsuario4 = new javax.swing.JPanel();
        jLabelUsuario4 = new javax.swing.JLabel();
        jPanelImagenUsuario5 = new javax.swing.JPanel();
        jLabelUsuario5 = new javax.swing.JLabel();
        jPanelImagenUsuario6 = new javax.swing.JPanel();
        jLabelUsuario6 = new javax.swing.JLabel();
        jPanelImagenUsuario7 = new javax.swing.JPanel();
        jLabelUsuario7 = new javax.swing.JLabel();
        jPanelImagenUsuario10 = new javax.swing.JPanel();
        jPanelImagenUsuario11 = new javax.swing.JPanel();
        jLabelUsuario8 = new javax.swing.JLabel();
        jLabelUsuario9 = new javax.swing.JLabel();
        jPanelImagenUsuario12 = new javax.swing.JPanel();
        jLabelUsuario10 = new javax.swing.JLabel();
        jPanelVueltaPerfil = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabelSeguidores.setText("Seguidores:");

        jPanelImagenUsuario1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelImagenUsuario1Layout = new javax.swing.GroupLayout(jPanelImagenUsuario1);
        jPanelImagenUsuario1.setLayout(jPanelImagenUsuario1Layout);
        jPanelImagenUsuario1Layout.setHorizontalGroup(
            jPanelImagenUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        jPanelImagenUsuario1Layout.setVerticalGroup(
            jPanelImagenUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jLabelUsuario1.setText("Usuario1");

        jPanelImagenUsuario2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelImagenUsuario2Layout = new javax.swing.GroupLayout(jPanelImagenUsuario2);
        jPanelImagenUsuario2.setLayout(jPanelImagenUsuario2Layout);
        jPanelImagenUsuario2Layout.setHorizontalGroup(
            jPanelImagenUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        jPanelImagenUsuario2Layout.setVerticalGroup(
            jPanelImagenUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jLabelUsuario2.setText("Usuario2");

        jPanelImagenUsuario3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelImagenUsuario3Layout = new javax.swing.GroupLayout(jPanelImagenUsuario3);
        jPanelImagenUsuario3.setLayout(jPanelImagenUsuario3Layout);
        jPanelImagenUsuario3Layout.setHorizontalGroup(
            jPanelImagenUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        jPanelImagenUsuario3Layout.setVerticalGroup(
            jPanelImagenUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jLabelUsuario3.setText("Usuario3");

        jPanelImagenUsuario4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelImagenUsuario4Layout = new javax.swing.GroupLayout(jPanelImagenUsuario4);
        jPanelImagenUsuario4.setLayout(jPanelImagenUsuario4Layout);
        jPanelImagenUsuario4Layout.setHorizontalGroup(
            jPanelImagenUsuario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        jPanelImagenUsuario4Layout.setVerticalGroup(
            jPanelImagenUsuario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jLabelUsuario4.setText("Usuario4");

        jPanelImagenUsuario5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelImagenUsuario5Layout = new javax.swing.GroupLayout(jPanelImagenUsuario5);
        jPanelImagenUsuario5.setLayout(jPanelImagenUsuario5Layout);
        jPanelImagenUsuario5Layout.setHorizontalGroup(
            jPanelImagenUsuario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        jPanelImagenUsuario5Layout.setVerticalGroup(
            jPanelImagenUsuario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jLabelUsuario5.setText("Usuario5");

        jPanelImagenUsuario6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelImagenUsuario6Layout = new javax.swing.GroupLayout(jPanelImagenUsuario6);
        jPanelImagenUsuario6.setLayout(jPanelImagenUsuario6Layout);
        jPanelImagenUsuario6Layout.setHorizontalGroup(
            jPanelImagenUsuario6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        jPanelImagenUsuario6Layout.setVerticalGroup(
            jPanelImagenUsuario6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jLabelUsuario6.setText("Usuario7");

        jPanelImagenUsuario7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelImagenUsuario7Layout = new javax.swing.GroupLayout(jPanelImagenUsuario7);
        jPanelImagenUsuario7.setLayout(jPanelImagenUsuario7Layout);
        jPanelImagenUsuario7Layout.setHorizontalGroup(
            jPanelImagenUsuario7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        jPanelImagenUsuario7Layout.setVerticalGroup(
            jPanelImagenUsuario7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jLabelUsuario7.setText("Usuario8");

        jPanelImagenUsuario10.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelImagenUsuario10Layout = new javax.swing.GroupLayout(jPanelImagenUsuario10);
        jPanelImagenUsuario10.setLayout(jPanelImagenUsuario10Layout);
        jPanelImagenUsuario10Layout.setHorizontalGroup(
            jPanelImagenUsuario10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        jPanelImagenUsuario10Layout.setVerticalGroup(
            jPanelImagenUsuario10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanelImagenUsuario11.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelImagenUsuario11Layout = new javax.swing.GroupLayout(jPanelImagenUsuario11);
        jPanelImagenUsuario11.setLayout(jPanelImagenUsuario11Layout);
        jPanelImagenUsuario11Layout.setHorizontalGroup(
            jPanelImagenUsuario11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        jPanelImagenUsuario11Layout.setVerticalGroup(
            jPanelImagenUsuario11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jLabelUsuario8.setText("Usuario6");

        jLabelUsuario9.setText("Usuario9");

        jPanelImagenUsuario12.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelImagenUsuario12Layout = new javax.swing.GroupLayout(jPanelImagenUsuario12);
        jPanelImagenUsuario12.setLayout(jPanelImagenUsuario12Layout);
        jPanelImagenUsuario12Layout.setHorizontalGroup(
            jPanelImagenUsuario12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        jPanelImagenUsuario12Layout.setVerticalGroup(
            jPanelImagenUsuario12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jLabelUsuario10.setText("Usuario10");

        javax.swing.GroupLayout jPanelVueltaPerfilLayout = new javax.swing.GroupLayout(jPanelVueltaPerfil);
        jPanelVueltaPerfil.setLayout(jPanelVueltaPerfilLayout);
        jPanelVueltaPerfilLayout.setHorizontalGroup(
            jPanelVueltaPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelVueltaPerfilLayout.setVerticalGroup(
            jPanelVueltaPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelImagenUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabelUsuario2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelImagenUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabelUsuario1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelImagenUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabelUsuario3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelImagenUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabelUsuario4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelImagenUsuario5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabelUsuario5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelImagenUsuario6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabelUsuario6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelImagenUsuario10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabelUsuario8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelImagenUsuario7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabelUsuario7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelImagenUsuario11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabelUsuario9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelImagenUsuario12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabelUsuario10)))
                .addGap(156, 156, 156))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jLabelSeguidores))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelVueltaPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelVueltaPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jPanelImagenUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabelUsuario1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelImagenUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabelUsuario2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelImagenUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabelUsuario3)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelImagenUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabelUsuario4)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelImagenUsuario5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabelUsuario5))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabelSeguidores)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelImagenUsuario10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabelUsuario8)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelImagenUsuario6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabelUsuario6)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelImagenUsuario7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabelUsuario7)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelImagenUsuario11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabelUsuario9)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelImagenUsuario12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabelUsuario10)))))
                .addContainerGap(218, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seguidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seguidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seguidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seguidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seguidores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelSeguidores;
    private javax.swing.JLabel jLabelUsuario1;
    private javax.swing.JLabel jLabelUsuario10;
    private javax.swing.JLabel jLabelUsuario2;
    private javax.swing.JLabel jLabelUsuario3;
    private javax.swing.JLabel jLabelUsuario4;
    private javax.swing.JLabel jLabelUsuario5;
    private javax.swing.JLabel jLabelUsuario6;
    private javax.swing.JLabel jLabelUsuario7;
    private javax.swing.JLabel jLabelUsuario8;
    private javax.swing.JLabel jLabelUsuario9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelImagenUsuario1;
    private javax.swing.JPanel jPanelImagenUsuario10;
    private javax.swing.JPanel jPanelImagenUsuario11;
    private javax.swing.JPanel jPanelImagenUsuario12;
    private javax.swing.JPanel jPanelImagenUsuario2;
    private javax.swing.JPanel jPanelImagenUsuario3;
    private javax.swing.JPanel jPanelImagenUsuario4;
    private javax.swing.JPanel jPanelImagenUsuario5;
    private javax.swing.JPanel jPanelImagenUsuario6;
    private javax.swing.JPanel jPanelImagenUsuario7;
    private javax.swing.JPanel jPanelVueltaPerfil;
    // End of variables declaration//GEN-END:variables
}
